---
- name: test if dhcpd_ipv4_interface is set correctly
  assert:
    that:
      - dhcpd_ipv4_interface is defined
    quiet: yes

- name: test if dhcpd_default_lease_time is set correctly
  assert:
    that:
      - dhcpd_default_lease_time is defined
      - dhcpd_default_lease_time is number
      - dhcpd_default_lease_time | int > 0
    quiet: yes

- name: test if dhcpd_max_lease_time is set correctly
  assert:
    that:
      - dhcpd_max_lease_time is defined
      - dhcpd_max_lease_time is number
      - dhcpd_max_lease_time | int > 0
    quiet: yes

- name: test if dhcpd_subnet_mask is set correctly
  assert:
    that:
      - dhcpd_subnet_mask is defined
    quiet: yes

- name: test if dhcpd_broadcast_address is set correctly
  assert:
    that:
      - dhcpd_broadcast_address is defined
    quiet: yes

- name: test if dhcpd_routers is set correctly
  assert:
    that:
      - dhcpd_routers is defined
    quiet: yes

- name: test if dhcpd_domain_name_servers is set correctly
  assert:
    that:
      - dhcpd_domain_name_servers is defined
    quiet: yes

- name: test if dhcpd_domain_search is set correctly
  assert:
    that:
      - dhcpd_domain_search is defined
    quiet: yes

- name: test if dhcpd_filename is set correctly
  assert:
    that:
      - dhcpd_filename is defined
    quiet: yes

- name: test if dhcpd_next_server is set correctly
  assert:
    that:
      - dhcpd_next_server is defined
    quiet: yes

- name: test if dhcpd_subnets is set correctly
  assert:
    that:
      - dhcpd_subnets is iterable
    quiet: yes
  when:
    - dhcpd_subnets is defined

- name: test if item in dhcpd_subnets is set correctly
  assert:
    that:
      - item.network is defined
      - item.netmask is defined
    quiet: yes
  loop: "{{ dhcpd_subnets }}"
  loop_control:
    label: "{{ item.network }}"
  when:
    - dhcpd_subnets is defined
