---
# tasks file for ansible-role-dhcpd
- name: include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "default.yml"

- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages }}"

- name: configure software
  copy:
    src: files/dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf

- name: start and enable software
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ services }}"
