---
# tasks file for dhcpd

- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: install dhcpd software
  package:
    name: "{{ dhcpd_packages }}"
    state: present

- name: configure defaults
  template:
    src: "{{ dhcpd_defaults_src }}"
    dest: "{{ dhcpd_defaults_dest }}"
    backup: yes
    mode: "0640"
  when:
    - ansible_os_family == "Debian" or
      ansible_distribution == "openSUSE Leap"
  notify: restart dhcpd

- name: configure software
  template:
    src: dhcpd.conf.j2
    dest: "{{ dhcpd_confdir }}/dhcpd.conf"
    backup: yes
    mode: "0640"
  notify: restart dhcpd

- name: start and enable software
  block:
    - name: start and enable software
      service:
        name: "{{ dhcpd_service }}"
        state: started
        enabled: yes
  rescue:
    # On Debian, the service starts, but reports broken.
    # This rescue block fixes just that.
    - name: install procps
      package:
        name: procps
        state: present

    - name: stop dhcpd
      command: pkill dhcpd

    - name: remove pid file
      file:
        path: /var/run/dhcpd.pid
        state: absent

    - name: start and enable software again
      service:
        name: "{{ dhcpd_service }}"
        state: started
        enabled: yes
