---
# handlers file for ansible-role-dhcpd
- name: restart isc-dhcp-server
  service:
    name: isc-dhcp-server
    state: restarted

- name: restart dhcpd
  service:
    name: dhcpd
    state: restarted
