---
# handlers file for dhcpd
- name: restart isc-dhcp-server
  service:
    name: isc-dhcp-server
    state: restarted
  when:
    - ansible_virtualization_type != "docker"

- name: restart dhcpd
  service:
    name: dhcpd
    state: restarted
  when:
    - ansible_virtualization_type != "docker"
