---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    dhcpd_subnets:
      - network: "{{ ansible_default_ipv4.network }}"
        netmask: "{{ ansible_default_ipv4.netmask }}"
        range_start: "{{ ansible_default_ipv4.network | ipmath(1) }}"
        range_end: "{{ ansible_default_ipv4.broadcast | ipmath(-1) }}"

  roles:
    - ansible-role-dhcpd
