---
- name: Prepare
  hosts: all
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.apt_autostart
    - role: robertdebock.code_dependencies

- name: Prepare controller
  hosts: localhost
  become: yes

  tasks:
    - name: install netaddr
      pip:
        name: netaddr
        state: present
