---
- name: Converge
  hosts: all
  gather_facts: false

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-dhcpd
      dhcpd_ipv4_interface: eth0
      dhcpd_default_lease_time: 60
      dhcpd_max_lease_time: 120
      dhcpd_subnet_mask: 255.255.255.0
      dhcpd_broadcast_address: 10.0.2.255
      dhcpd_routers: 10.0.2.1
      dhcpd_domain_name_servers: 10.0.2.1
      dhcpd_domain_search: install
      dhcpd_filename: pxelinux.0
      dhcpd_next_server: 10.0.2.1
      dhcpd_subnets:
        - network: 10.0.2.0
          netmask: 255.255.255.0
          range_start: 10.0.2.127
          range_end: 10.0.2.254
